<?php


/**
 * This class adds structure of 'design' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Feb  2 15:30:52 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DesignMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DesignMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(DesignPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(DesignPeer::TABLE_NAME);
		$tMap->setPhpName('Design');
		$tMap->setClassname('Design');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('design_id_seq');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 30);

		$tMap->addForeignKey('OWNER', 'Owner', 'VARCHAR', 'system_user', 'USERNAME', true, 30);

		$tMap->addColumn('XML_CODE', 'XmlCode', 'LONGVARCHAR', false, null);

	} // doBuild()

} // DesignMapBuilder
