default:
  http_metas:
    content-type: text/html

  metas:
    title:        SILICIO
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow

  stylesheets:    [ext/ext-all.css]

  javascripts:    [ext/adapter/ext/ext-base.js, ext/ext-all-debug.js]

  has_layout:     on
  layout:         layout
