dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        pgsql:dbname=silicio_db;host=localhost
      username:   silicio_system
      password:   silicio_password
      encoding:   utf8
      persistent: true
      pooling:    true
